# Generated by Django 6.0.2 on 2026-07-04 09:49

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Costomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام مشتری')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='شماره تلفن')),
                ('desacription', models.CharField(max_length=1500, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'لیسست مشتریان',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', ckeditor.fields.RichTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CuostomerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True, verbose_name='عناوان آگهی درخواست')),
                ('dealtype', models.CharField(choices=[('SALE_PROPERTY', 'فروش مسکونی'), ('SALE_BUSINESS', 'فروش اداری تجاری'), ('RENT_PROPERTY', 'رهن و اجاره مسکونی'), ('RENT_BUSINESS', 'رهن و اجاره اداری نجاری')], default='SALE_PROPERTY', max_length=50)),
                ('status', models.CharField(choices=[('active', 'فعال'), ('in_progress', 'در حال پیگیری'), ('closed', 'بسته شده'), ('canceled', 'لغو شده')], default='active', max_length=20, verbose_name='وضعیت آگهی')),
                ('min_area', models.IntegerField(blank=True, null=True, verbose_name='حداقل متراژ')),
                ('max_area', models.IntegerField(blank=True, null=True, verbose_name='حداکثر متراژ')),
                ('mortgage_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ رهن')),
                ('rent_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='اجاره ماهیانه')),
                ('min_price', models.BigIntegerField(blank=True, null=True, verbose_name='حداقل قیمت')),
                ('max_price', models.BigIntegerField(blank=True, null=True, verbose_name='حداکثر قیمت')),
                ('rooms', models.IntegerField(blank=True, null=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='leads.costomer')),
            ],
            options={
                'verbose_name': 'درخواست ملک',
                'verbose_name_plural': 'درخواست هاس املاک',
                'ordering': ['-created_at'],
            },
        ),
    ]
