# Generated by Django 6.0.2 on 2026-07-04 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        ('property', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cuostomerrequest',
            name='district',
            field=models.ManyToManyField(to='property.district', verbose_name='انتخاب محله'),
        ),
        migrations.AddField(
            model_name='cuostomerrequest',
            name='property_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.propertycategory'),
        ),
        migrations.AddField(
            model_name='requestfollowup',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='مشاور ثبت کننده'),
        ),
        migrations.AddField(
            model_name='requestfollowup',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='leads.costomer', verbose_name='مشتری'),
        ),
        migrations.AddField(
            model_name='requestfollowup',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followup', to='leads.cuostomerrequest', verbose_name='درخواست مرتبط'),
        ),
    ]
