# Generated by Django 6.0.2 on 2026-07-06 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costomer',
            options={'ordering': ['-created_at'], 'verbose_name': 'مشتری', 'verbose_name_plural': 'لیست مشتریان'},
        ),
        migrations.AlterModelOptions(
            name='cuostomerrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'درخواست ملک', 'verbose_name_plural': 'درخواست های املاک'},
        ),
        migrations.RenameField(
            model_name='costomer',
            old_name='desacription',
            new_name='description',
        ),
    ]
