# Generated by Django 6.0.2 on 2026-07-08 17:53

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_alter_costomer_options_and_more'),
        ('property', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنولن کار')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='توضیحات')),
                ('task_type', models.CharField(choices=[('call', 'تماس'), ('follow_up', 'پیگیری'), ('visit', 'بازدید'), ('send_file', 'ارسال فایل'), ('meeting', 'جلسه'), ('reminder', 'یادآوری'), ('custom', 'سفارشی')], default='custom', max_length=30, verbose_name='نوع مار')),
                ('priority', models.CharField(choices=[('low', 'پایین'), ('medium', 'متوسط'), ('high', 'زیاد'), ('urgent', 'فوری')], default='medium', max_length=30, verbose_name='اولویت')),
                ('status', models.CharField(choices=[('todo', 'درحال انجام'), ('done', 'لنجلم شده'), ('cancelled', 'لغو شده'), ('mised', 'انجام نشده')], default='todo', max_length=30, verbose_name='وضعیت')),
                ('due_date', models.DateField(verbose_name='تاریخ انجام')),
                ('due_time', models.TimeField(blank=True, null=True, verbose_name='ساعت انجام')),
                ('is_auto_created', models.BooleanField(default=False, verbose_name='ایجاد خودکار')),
                ('sms_reminder_enabled', models.BooleanField(default=False, verbose_name='پیامک یاداوری')),
                ('sms_sent', models.BooleanField(default=False, verbose_name='پیامک ارسال شده')),
                ('sms_sent_as', models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال پیامک')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان انجام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents_tasks', to=settings.AUTH_USER_MODEL, verbose_name='مشاور')),
                ('related_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='leads.costomer', verbose_name='مشتری مرتبط')),
                ('related_property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='property.propertylisting', verbose_name='ملک مرتبط')),
                ('related_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='leads.cuostomerrequest', verbose_name='درخواست مرتبط')),
            ],
            options={
                'verbose_name': 'کار',
                'verbose_name_plural': 'کار ها',
                'ordering': ['status', 'due_date', 'due_time', '-created_at'],
            },
        ),
    ]
