# Generated by Django 6.0.2 on 2026-07-31 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_agenttask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenttask',
            name='task_type',
            field=models.CharField(choices=[('call', 'تماس'), ('follow_up', 'پیگیری'), ('visit', 'بازدید'), ('send_file', 'ارسال فایل'), ('meeting', 'جلسه'), ('reminder', 'یادآوری'), ('custom', 'سفارشی')], default='custom', max_length=30, verbose_name='نوع کار'),
        ),
    ]
