# Generated by Django 6.0.2 on 2026-04-04 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_agent',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='مشاور'),
        ),
    ]
