# Generated by Django 6.0.2 on 2026-07-31 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['-created_at'], 'verbose_name': 'بنر', 'verbose_name_plural': 'بنرها'},
        ),
        migrations.AddField(
            model_name='banner',
            name='about_url',
            field=models.CharField(default='/about/', max_length=300, verbose_name='لینک معرفی سایت'),
        ),
        migrations.AddField(
            model_name='banner',
            name='cities_url',
            field=models.CharField(default='/cities/', max_length=300, verbose_name='لینک جستجوی ملک در شهرها'),
        ),
        migrations.AddField(
            model_name='banner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AddField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AddField(
            model_name='banner',
            name='login_url',
            field=models.CharField(default='/login/', max_length=300, verbose_name='لینک ورود به سایت'),
        ),
        migrations.AddField(
            model_name='banner',
            name='properties_url',
            field=models.CharField(default='/properties/', max_length=300, verbose_name='لینک ورود به بخش املاک'),
        ),
        migrations.AddField(
            model_name='banner',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='banners/', verbose_name='تصویر بنر'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='زیرعنوان'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
    ]
