# Generated by Django 6.0.2 on 2026-08-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_banner_options_banner_about_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان لینک')),
                ('url', models.CharField(help_text='مثال: /properties/search/ یا آدرس کامل اینترنتی', max_length=300, verbose_name='آدرس (url)')),
                ('order', models.PositiveIntegerField(default=0, help_text='هرچه عدد کمتر باشد، لینک جلوتر نمایش داده می\u200cشود.', verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'لینک سریع',
                'verbose_name_plural': 'لینک\u200cهای سریع',
                'ordering': ['order', 'id'],
            },
        ),
    ]
