# Generated by Django 6.0.2 on 2026-07-04 09:49

import ckeditor.fields
import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='امکانات')),
            ],
            options={
                'verbose_name': 'امکانات',
                'verbose_name_plural': 'امکانات',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='شهر')),
            ],
            options={
                'verbose_name': 'شهر',
                'verbose_name_plural': 'شهر',
            },
        ),
        migrations.CreateModel(
            name='PropertyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نوع کاربری ملک')),
            ],
            options={
                'verbose_name': 'کاربری ملک',
                'verbose_name_plural': 'کاربری های ملک',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='استان')),
            ],
            options={
                'verbose_name': 'استان',
                'verbose_name_plural': 'استان',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='محله')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='property.city', verbose_name='شهر')),
            ],
            options={
                'verbose_name': 'محله',
                'verbose_name_plural': 'محله ها',
            },
        ),
        migrations.CreateModel(
            name='PropertyListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان آگهی')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=200, null=True, unique=True, verbose_name='اسلاگ')),
                ('description', ckeditor.fields.RichTextField(blank=True, max_length=500, null=True, verbose_name='توضیحات ملک')),
                ('status', models.CharField(choices=[('DRAFT', 'پیش نویس'), ('AVAILABLE', 'انتشار یافته'), ('SOLD', 'واگذار شده')], default='DRAFT', max_length=20, verbose_name='وضعیت انتشار')),
                ('owner_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام مالک /موجر')),
                ('owner_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تماس مالک')),
                ('deal_type', models.CharField(choices=[('SALE_PROPERTY', 'فروش مسکونی'), ('SALE_BUSINESS', 'فروش اداری تجاری'), ('RENT_PROPERTY', 'رهن و اجاره مسکونی'), ('RENT_BUSINESS', 'رهن و اجاره اداری نجاری')], default='SALE_PROPERTY', max_length=25, verbose_name='نوع معامله')),
                ('area', models.PositiveIntegerField(blank=True, null=True, verbose_name='متراژ(متر مربع)')),
                ('year_built', models.PositiveIntegerField(blank=True, null=True, verbose_name='سال ساخت')),
                ('rooms', models.PositiveIntegerField(default=1, verbose_name='تعداد اتاق')),
                ('total_floors', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد کل طبقات')),
                ('selling_price', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='قیمت کل فروش')),
                ('mortgage_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ رهن')),
                ('rent_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='اجاره ماهیانه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت انتشار')),
                ('PROPERTY_TYPE', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='property.propertycategory', verbose_name='نوع ملک')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing', to=settings.AUTH_USER_MODEL, verbose_name='مشاور ثبت کننده ')),
                ('amenities', models.ManyToManyField(blank=True, to='property.amenity', verbose_name='امکانات')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property.district', verbose_name='محله')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='تگ ها')),
            ],
            options={
                'verbose_name': 'آگهی ملک',
                'verbose_name_plural': 'آگهی های املاک',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/galleries/%Y/%m', verbose_name='تصویر')),
                ('is_cover', models.BooleanField(default=False, verbose_name='تصویر اصلی')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='property.propertylisting', verbose_name='آگهی مرتبط')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='property.province', verbose_name='ایتان'),
        ),
    ]
